### ISSUE TITLE
Updating Payment Methods in Bolt Card Factory doesn't work

### ISSUE THREAD

**Issue by rockstardev** [NicolasDorier/boltcards-plugin#1]
It's very easy to replicate the issue. Here is the video demonstrating the problem:
https://github.com/NicolasDorier/boltcards-plugin/assets/5191402/89168ad4-6fc6-4506-a35d-96d7242cf58d

**Comment by johnheenan** [comment]
In addition, if only one payment method was initially allowed, there is no choice to add in more when editing a bolt card factory:

![image](https://github.com/NicolasDorier/boltcards-plugin/assets/22131790/4143e704-18b8-4210-9fdb-440a5f1eaf29)

Also, any newly created boltcard factories will have the same single choice.

Also, unticking the single choice and saving the factory gives an exception:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'UpdateBoltcardFactory' was not found. The following locations were searched:
/Views/UIBoltcardFactory/UpdateBoltcardFactory.cshtml
/Views/Shared/UpdateBoltcardFactory.cshtml
/Pages/Shared/UpdateBoltcardFactory.cshtml
/UpdateBoltcardFactory.cshtml
```

**Comment by johnheenan** [comment]
Correction, to add in more payment methods I need to add in a new payment method for the store first. However, still buggy

This save change is successful:
![image](https://github.com/NicolasDorier/boltcards-plugin/assets/22131790/e2a0d508-becd-41e6-b795-accaa38654fa)

This save change fails (goes back to above)
![image](https://github.com/NicolasDorier/boltcards-plugin/assets/22131790/31aea0c3-149d-4f23-8db4-ab75949dcc9e)

This save change results in an exception instead of an invalid state notice and goes back to top state:
![image](https://github.com/NicolasDorier/boltcards-plugin/assets/22131790/5b83cfbf-0f17-43d6-9fe2-a9c19be189c4)
